services:
  app:
    build: .
    container_name: zim_rates_app
    expose:
      - 3000
    ports:
      - '3000:3000'

  db:
    image: mysql
    container_name: zim_rate_db
    environment:
      - MYSQL_ROOT_HOST=${HOST}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
