name: Get bank rates
on:
  workflow_dispatch:

jobs:
  Get-bank-rates:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/services
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'
      - run: npm install
      - name: create env file
        run: |
          touch .env
          echo "SB_HOST=${SB_HOST}" >> .env
          echo "SB_DATABASE=${SB_DATABASE}" >> .env
          echo "SB_PORT=${SB_PORT}" >> .env
          echo "SB_DB_PASSWORD=${SB_DB_PASSWORD}" >> .env
          echo "SB_USER=${SB_USER}" >> .env
          echo "SB_DB_URL=${SB_DB_URL}" >> .env
      - run: npm run get-rates
