name: Get bank rates
run-name: Rates creator
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: services

jobs:
  Get-bank-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '21.6.2'
      - run: echo "Running Script"
      - run: npm run get-rates
