name: Get bank rates
on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

env:
  PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
  PROD_DB_DATABASE: ${{ secrets.PROD_DB_DATABASE }}
  PROD_DB_PORT: ${{ secrets.PROD_DB_PORT }}
  PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
  PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
  PROD_DB_URL: ${{ secrets.PROD_DB_URL }}

jobs:
  Get-bank-rates:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/services
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'
      - run: npm install
      - run: export NODE_ENV=production && npm run get-rates
