name: Get bank rates
run-name: Rates creator
on:
  workflow_dispatch:

jobs:
  Get-bank-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '21.6.2'
      - name: Run Script
        run: npm run get-rates
        working-directory: services
