name: Get bank rates
on:
  workflow_dispatch:

env:
  SB_HOST: ${{ secrets.SB_HOST }}
  SB_DATABASE: ${{ secrets.SB_DATABASE }}
  SB_PORT: ${{ secrets.SB_PORT }}
  SB_DB_PASSWORD: ${{ secrets.SB_DB_PASSWORD }}
  SB_USER: ${{ secrets.SB_USER }}
  SB_DB_URL: ${{ secrets.SB_DB_URL }}

jobs:
  Get-bank-rates:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/services
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'
      - run: npm install
      - name: echo envs
        run: |
          echo "${SB_HOST}"
          echo "${SB_DATABASE}"
          echo "${SB_PORT}"
          echo "${SB_DB_PASSWORD}"
          echo "${SB_USER}"
          echo "${SB_DB_URL}"
      - name: create env file
        run: |
          touch .env
          echo "SB_HOST=${SB_HOST}" >> .env
          echo "SB_DATABASE=${SB_DATABASE}" >> .env
          echo "SB_PORT=${SB_PORT}" >> .env
          echo "SB_DB_PASSWORD=${SB_DB_PASSWORD}" >> .env
          echo "SB_USER=${SB_USER}" >> .env
          echo "SB_DB_URL=${SB_DB_URL}" >> .env
      - run: npm run get-rates
