name: Get bank rates
on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

env:
  HOST: ${{ secrets.HOST }}
  DATABASE: ${{ secrets.DATABASE }}
  PORT: ${{ secrets.PORT }}
  PASSWORD: ${{ secrets.PASSWORD }}
  DB_USER: ${{ secrets.DB_USER }}
  URL: ${{ secrets.URL }}

jobs:
  Get-bank-rates:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/services
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'
      - run: npm install
      - run: export NODE_ENV=production && npm run get-rates
