name: Get bank rates
on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  Get-bank-rates:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ${{ github.workspace }}/services
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'
      - run: npm install
      - run: export NODE_ENV=production && npm run get-rates
